### ISSUE TITLE
Is it ok to copy paste your EFI to mine?

### ISSUE THREAD

**Issue by wtjin1992** [Galeas/hackintosh#1]
Hi there, thanks for your well-organized tutorial. I have a very similar build as yours: Prime z370-a + 8700K + RX580, and I'm currently running a mojave on it. I want to upgrade to Catalina and I'm wondering if it's ok to just copy paste your EFI to my EFI partition? Is there anything in the config.plist I need to modify or pay attention to? Thanks for your help!

**Comment by Galeas** [comment]
I think so, but you definitely should update the bootloader and make a backup of your current EFI so you can rollback if something will gone wrong.
